spring:
  banner:
    location: classpath:/banners/dev.txt
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: "org.testcontainers.jdbc.ContainerDatabaseDriver"
    url: "jdbc:tc:postgresql:11.1:///integration-tests-db"